---
# ansible-playbook -i workshop-tp-answers/inventories/dev/tp3 workshop-tp-answers/tp3/setup-petclinic-env.yml -vv
- hosts:                               petclinic_loadbalancer_servers
  tasks:
    - name:                            Install Nginx
      become:                          yes
      become_method:                   sudo
      ansible.builtin.apt:
        name:                          nginx
        state:                         present
        update_cache:                  yes
        cache_valid_time:              86340

    - name:                            Define Nginx as a Service
      become:                          yes
      become_method:                   sudo
      ansible.builtin.service:
        name:                          nginx
        state:                         started
        enabled:                       yes

    - name:                            Copy petclinic nginx conf to nginx sites-available
      become:                          yes
      become_method:                   sudo
      ansible.builtin.copy:
        src:                           nginx-petclinic.conf
        dest:                          /etc/nginx/sites-available/petclinic.conf
      notify:
      - event__nginx__configuration_changed

    - name:                            Validate nginx configuration
      become:                          yes
      become_method:                   sudo
      ansible.builtin.command:
        cmd:                           nginx -t

    - name:                            Enable petclinic site to be served by nginx
      become:                          yes
      become_method:                   sudo
      ansible.builtin.file:
        src:                           /etc/nginx/sites-available/petclinic.conf
        dest:                          /etc/nginx/sites-enabled/petclinic.conf
        state:                         link
      notify:
      - event__nginx__configuration_changed

  handlers:
    - name:                            event__nginx__configuration_changed
      become:                          yes
      become_method:                   sudo
      ansible.builtin.service:
        name:                          nginx
        state:                         reloaded

- hosts:                               petclinic_database_servers
  gather_facts: false
  connection: local
  tasks:
    - name: Create petclinic user
      postgresql_user:
        name: petclinic
        password: petclinic
        encrypted: yes
        port: 5432
        state: present
        login_host: bdddev01
        login_user: postgres
        login_password: postgres

    - name: Create petclinic database
      postgresql_db:
        name: petclinic
        encoding: "UTF-8"
        owner: petclinic
        port: 5432
        state: present
        login_host: bdddev01
        login_user: postgres
        login_password: postgres

- hosts:                               petclinic_application_servers
  tasks:
    - name:                            Install OpenJdk
      become:                          yes
      become_method:                   sudo
      ansible.builtin.apt:
        name:                          openjdk-17-jdk
        state:                         present
        update_cache:                  yes
        cache_valid_time:              86340

    - name: Creates /apps/petclinic/binaries directory for petclinic deployment
      become:                          yes
      become_method:                   sudo
      ansible.builtin.file:
        path: /apps/petclinic/binaries
        state: directory
        recurse: yes
        
    - name: Creates /apps/petclinic/scripts directory for petclinic deployment
      become:                          yes
      become_method:                   sudo
      ansible.builtin.file:
        path: /apps/petclinic/scripts
        state: directory
        recurse: yes

    - name: Copy binary for petclinic deployment
      become:                          yes
      become_method:                   sudo
      ansible.builtin.copy:
        src: /home/ansible/petclinic/binaries/spring-petclinic.jar
        dest: /apps/petclinic/binaries/spring-petclinic.jar
 
    - name: Copy start-petclinic-inmemory-db.sh for petclinic deployment
      become:                          yes
      become_method:                   sudo
      ansible.builtin.copy:
        src: /home/ansible/workspace/start-petclinic-inmemory-db.sh
        dest: /apps/petclinic/scripts/start-petclinic-inmemory-db.sh

    - name: Copy start-petclinic-postgresql-db.sh for petclinic deployment
      become:                          yes
      become_method:                   sudo
      ansible.builtin.copy:
        src: /home/ansible/workspace/start-petclinic-postgresql-db.sh
        dest: /apps/petclinic/scripts/start-petclinic-postgresql-db.sh

    - name: Copy stop-petclinic.sh for petclinic deployment
      become:                          yes
      become_method:                   sudo
      ansible.builtin.copy:
        src: /home/ansible/workspace/stop-petclinic.sh
        dest: /apps/petclinic/scripts/stop-petclinic.sh
