---
# ansible-playbook -i workshop-tp-answers/inventories/dev/tp4 workshop-tp-answers/tp4/run-petclinic-with-postgresql-db.yml
- hosts: petclinic_application_servers
  tasks:
    - name:     shutdown PetClinic, if launched
      command:
        chdir:  /apps/petclinic
        cmd:    sh scripts/stop-petclinic.sh
      ignore_errors:  yes

    - name:     run PetClinic
      command:
        chdir:  /apps/petclinic
        cmd:    sh scripts/start-petclinic-postgresql-db.sh

