- name:                            Install OpenJdk
  become:                          yes
  become_method:                   sudo
  ansible.builtin.apt:
    name:                          openjdk-17-jdk
    state:                         present
    update_cache:                  yes
    cache_valid_time:              86340
