
- name:                     on__petclinic_lb__configuration_changed
  become:                   yes
  become_method:            sudo
  ansible.builtin.service:
    name:                   nginx
    state:                  reloaded
  listen:                   event__petclinic_lb__configuration_changed
