---
# ansible-playbook -i workshop-tp-answers/inventories/_local bonus/playbooks/build-petclinic.yml --ask-become-pass -vv
- hosts:                     localhost
  tasks:
    - name:                  Install Git + maven
      become:                yes
      become_method:         sudo
      ansible.builtin.apt:
        name:
          - git
          - maven
          - openjdk-17-jdk
        state:               present
        update_cache:        '{{ apt_update_cache }}'
        cache_valid_time:    '{{ apt_cache_ttl }}'

    - name:                  Create _src directory if it does not exist
      ansible.builtin.file:
        path:                '{{ build_petclinic_src_dir }}'
        state:               directory

    - name:                  Create _git directory if it does not exist
      ansible.builtin.file:
        path:                '{{ build_git_repo_root_dir }}'
        state:               directory

    - name:                  Clone a repo with separate git directory
      ansible.builtin.git:
        repo:                https://github.com/spring-projects/spring-petclinic.git
        dest:                '{{ build_petclinic_src_dir }}'
        separate_git_dir:    '{{ build_git_repo_root_dir }}/spring-petclinic.git'

    - name:                  build PetClinic, cf. https://github.com/spring-projects/spring-petclinic
      command:
        chdir:               '{{ build_petclinic_src_dir }}'
        cmd:                 ./mvnw package
