---
# tasks file for app_install
- name:                            Install OpenJdk
  become:                          true
  become_method:                   sudo
  ansible.builtin.apt:
    name:                          openjdk-17-jdk
    state:                         present
    update_cache:                  true
    cache_valid_time:              86340

- name: Creates /apps/petclinic/binaries directory for petclinic deployment
  become:                          true
  become_method:                   sudo
  ansible.builtin.file:
    path: /apps/petclinic/binaries
    state: directory
    recurse: yes
    
- name: Creates /apps/petclinic/scripts directory for petclinic deployment
  become:                          true
  become_method:                   sudo
  ansible.builtin.file:
    path: /apps/petclinic/scripts
    state: directory
    recurse: yes

- name: Copy binary for petclinic deployment
  become:                          true
  become_method:                   sudo
  ansible.builtin.copy:
    src: /home/ansible/petclinic/binaries/spring-petclinic.jar
    dest: /apps/petclinic/binaries/spring-petclinic.jar

- name: Copy start-petclinic-inmemory-db.sh for petclinic deployment
  become:                          true
  become_method:                   sudo
  ansible.builtin.copy:
    src: /home/ansible/workspace/start-petclinic-inmemory-db.sh
    dest: /apps/petclinic/scripts/start-petclinic-inmemory-db.sh

- name: Copy start-petclinic-postgresql-db.sh for petclinic deployment
  become:                          true
  become_method:                   sudo
  ansible.builtin.copy:
    src: /home/ansible/workspace/start-petclinic-postgresql-db.sh
    dest: /apps/petclinic/scripts/start-petclinic-postgresql-db.sh

- name: Copy stop-petclinic.sh for petclinic deployment
  become:                          true
  become_method:                   sudo
  ansible.builtin.copy:
    src: /home/ansible/workspace/stop-petclinic.sh
    dest: /apps/petclinic/scripts/stop-petclinic.sh
